var artists = [
    "Caillebotte",
    "Cassatt",
    "Cezanne",
    "Dada",
    "Dali",
    "Delacroix",
    "Duchamp",
    "Durer",
    "Gauguin",
    "Giacometti",
    "Haacke",
    "Goya",
    "Kahlo",
    "Kirchner",
    "Klimt",
    "Magritte",
    "Malevich",
    "Manet",
    "Matisse",
    "Miro",
    "Monet",
    "Picasso",
    "Pollock",
    "Rembrandt",
    "Warhol",
    "Wyeth"  
];

var descriptions = [
    "a construct",
    "a commentary",
    "a critique",
    "a criticism",
    "a treatise",
    "a discourse",
    "a reflection",
    "an exegesis",
    "an exposition",
    "a dichotomy",
    "a contemplation",
    "a meditation",
    "a rumination",
    "a cognitation",
    "a musing",
    "a study",
    "a reflection",
    "a reverie",
    "an abstraction",
    "an eludication",
    "a portal",
    "a parallel",
    "an analog",
    "telling",
    "evocative"
];

var phrases = [
"gender bias & heteronormativity",
"breaking down the binaries",
"evocative postmodernism",
"kitsch and fetishism",
"German expressionist theory",
"the constructivist sentiment",
"an acute perspective of fauvism",
"a primitivist rendering",
"spacial depth and symmetry",
"the frenzied pace of city life",
"an abstraction of classism",
"ethereal synergism",
"the avant-garde philosophy",
"the withered self-representation"
];